# Use the official Node.js image as the base image
FROM node:latest
RUN touch jb-was-here

# Expose the default Vite development port (optional)
#EXPOSE 3000

# Start a shell or your application when the container runs
#CMD ["/bin/bash"]